language: go

go:
  - "1.9"
  - "1.10"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -t -v ./...

install:
  - make setup

script:
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
